[project]
name = "04-rag-notion-search"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "ddudi", email = "ddudios@naver.com" }
]
requires-python = ">=3.11"
dependencies = [
    "anthropic>=1.2.0",
    "notion-client>=3.1.0",
    "numpy>=2.4.6",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
]

[project.scripts]
04-rag-notion-search = "04_rag_notion_search:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
